name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install
      
      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.API_FTP_SERVER }}
          username: ${{ secrets.API_FTP_USERNAME }}
          password: ${{ secrets.API_FTP_PASSWORD }}
          # local-dir: dist/
          server-dir: /api/
          
