name: Running Deployment Pipeline
run-name: ${{github.actor}} in ${{github.ref}}
on:
    push:
    workflow_dispatch:
jobs:
    deploying:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: npm install